Separated Card components into multiple components
hackforla/CivicTechJobs pull request #213
Opened 2022-04-06 00:58 UTC by NickTSA

closes #175 

Fixes #

Created separate js and scss files for cards components.
Updated imports within components.js

### Changes

- Changes to file structure only 
- File imports changed for cards components

2022-04-06 16:58 UTC, Aveline-art requested changes
Thanks for working on this.

As per the second action item, please split all cards into different files and name the files after the components. In total there should be 3 files for the cards.

2022-04-13 02:04 UTC, NickTSA commented
@Aveline-art ready

2022-04-13 14:32 UTC, Aveline-art commented
Hi @NickTSA . Let me know if this is how the demo endpoint appears on your screen appears as well.

![description example](https://user-images.githubusercontent.com/62368440/163203968-20f407fa-1a14-4c79-8155-725806958963.png)

2022-04-16 22:33 UTC, NickTSA commented
@Aveline-art Ready 👍

2022-04-17 00:54 UTC, Aveline-art requested changes
Just a couple of small fixes and this should be good to go!

2022-04-17 00:54 UTC, Aveline-art commented on app/frontend/src/components/Cards/Cards.js
> +export { CopCard };
Let's rename this file after the component

2022-04-17 00:54 UTC, Aveline-art commented on app/frontend/src/components/Cards/_Cards.scss
> -
Let's rename this file after the component

2022-04-17 00:54 UTC, Aveline-art commented on app/frontend/src/components/Cards/InnerCopCard.js
> +
Component is missing propTypes information.

2022-04-18 02:18 UTC, NickTSA commented
ready

2022-04-18 15:16 UTC, Aveline-art commented on app/frontend/src/components/Cards/Cards.js
> +export { CopCard };
@NickTSA This has not been resolved yet. Lets rename this **file** after the component.

2022-04-18 15:20 UTC, Aveline-art approved these changes
@NickTSA You're very close to finishing this, but it seems you misread my previous corrections. Please be very careful! It is a big waste of our time to correct the same thing repeatedly. Please also let me know if my corrections can be any more clear. I do not want misreadings to happen consistently.

2022-04-18 15:20 UTC, Aveline-art commented on app/frontend/src/components/Cards/_InnerCopCards.scss
> +}
Let's keep names consistent and use singular rather than plural for file name.

2022-04-18 15:20 UTC, Aveline-art commented on app/frontend/src/components/Cards/_CopCards.scss
> -}
Let's keep names consistent and use singular rather than plural for file name.

2022-04-18 15:20 UTC, Aveline-art requested changes
Corrected a mistaken approval.

2022-04-18 18:36 UTC, NickTSA commented
ok I removed the plural names @Aveline-art

2022-04-18 19:40 UTC, Aveline-art commented
@NickTSA None of the changes have been made. Have you checked and verified it through the [files changes ](https://github.com/hackforla/CivicTechJobs/pull/213/files)tab.

2022-04-18 21:56 UTC, NickTSA commented
@Aveline-art Okay its ready

2022-04-18 22:01 UTC, NickTSA commented
@Aveline-art Btw the "cards" js component was already plural. I don't know if you want me to change that from its original name.

2022-04-18 22:24 UTC, Aveline-art commented
@NickTSA There should no longer be a `Cards.js` as the file needs to be named after the component. If you want to rename the component to `cards`, you need to provide justification as it is beyond the scope of this issue.

2022-04-18 22:27 UTC, Aveline-art commented on app/frontend/src/components/Cards/_CopCard.scss
> -**********************************/
Let's also add back these comment markers.

2022-04-18 22:48 UTC, NickTSA commented
@Aveline-art done

2022-04-19 03:03 UTC, Aveline-art commented
@NickTSA I see that you have decided to rename the component, `CopCard` to just `Card`. Can you tell me a bit more why this change was needed or preferable?

2022-04-19 03:10 UTC, NickTSA commented
@Aveline-art My mistake, I changed it to just Cards.

2022-04-20 00:58 UTC, Aveline-art commented
@NickTSA I am going to close this PR, as it has gone through a lot of revisions but it is not getting any closer to a merge-able state.

Thank you for working on this. I will unassign you from the issue as well.

2022-04-20 00:58 UTC, closed without merging